const API_KEY = "37453a5d9e85cb4793267590";

const input = document.getElementById("input-amount");

const result_text = document.getElementById("result-text");
const result = document.getElementById("result");
const update_time = document.getElementById("update-time");
const convert_btn = document.getElementById("convert-btn");
const curr_from = document.getElementById("from-dropdown");
const curr_to = document.getElementById("to-dropdown");
function convert() {
  const url = `https://v6.exchangerate-api.com/v6/${API_KEY}/pair/${curr_from.value}/${curr_to.value}`;

  return fetch(url)
    .then((response) => {
      return response.json();
    })
    .then((data) => {
      return data;
    })
    .catch((error) => {
      alert("some issue occured", error);
    });
}
// convert UTC time to local
// generated by AI
function convertUTCToLocalTime(utcTimestamp) {
    const utcDate = new Date(utcTimestamp);
    const localTime = new Date(utcDate.getTime() + utcDate.getTimezoneOffset() * 60000);
    return localTime;
  }

function showResult() {
  result_text.innerHTML = "";
  result.innerHTML = "";
  update_time.innerHTML = "";
  convert().then((data) => {
    if (input.value) {
      result_text.innerHTML = `1 ${curr_from.value} equals to ${data.conversion_rate} `;
      result.innerHTML =
        data.conversion_rate * input.value + " " + curr_to.value;
      update_time.innerHTML =
        "Last updated " + convertUTCToLocalTime(data.time_last_update_utc);
      console.log("clied");
    }
  });
}
convert_btn.addEventListener("click", showResult);
